---
- hosts: all
  become: yes
  tasks:
  - name: Update APT package list
    apt:
      update_cache: yes

  - name: Install Nginx
    apt:
      name: nginx
      state: present

  - name: Copy Website Files
    copy:
      src: ./dojo-jump
      dest: /var/www/html/
      mode: '0644'